[Git] Update "git site" alias to work with SSH connection

diff --git a/applications/git/gitconfig b/applications/git/gitconfig
--- a/applications/git/gitconfig
+++ b/applications/git/gitconfig
@@ -57,15 +57,19 @@
     dt = difftool --dir-diff
     dtv = difftool -v vimdiff
     cnv = !"version=$(cat version); git commit --include version --message \"[Version] $version\""
-    site = !"current_branch=$(git branch --show-current) && \
-             if git rev-parse --quiet --verify \"refs/remotes/origin/${current_branch}\" > /dev/null; \
-             then \
-               url=$(git config --get remote.origin.url | sed 's|git@\\(.*\\):\\(.*\\).git|https://\\1/\\2/tree/'${current_branch}'|'); \
-             else \
-               current_branch=\"master\"; \
-               url=$(git config --get remote.origin.url | sed 's|git@\\(.*\\):\\(.*\\).git|https://\\1/\\2/tree/'${current_branch}'|'); \
-             fi; \
-             xdg-open $url 2>/dev/null"
+    site = "!current_branch=$(git branch --show-current) && \
+      if git rev-parse --quiet --verify \"refs/remotes/origin/${current_branch}\" > /dev/null; then \
+        url=$(git config --get remote.origin.url | sed 's|git@\\(.*\\):\\(.*\\).git|https://\\1/\\2/tree/'${current_branch}'|'); \
+      else \
+        current_branch=\"master\"; \
+        url=$(git config --get remote.origin.url | sed 's|git@\\(.*\\):\\(.*\\).git|https://\\1/\\2/tree/'${current_branch}'|'); \
+      fi; \
+      if [ \"$SSH_CONNECTION\" ]; then \
+        echo \"You are on a remote device. The project URL is: $url\"; \
+        echo \"$url\" | xclip -selection clipboard >/dev/null 2>&1 && echo \"   URL copied to clipboard.\"; \
+      else \
+        xdg-open \"$url\" >/dev/null 2>&1 || echo \"Failed to open browser. The project URL is: $url\"; \
+      fi"
     root = rev-parse --show-toplevel
 [diff]
     tool = meld
